import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {renderPages} from './pages.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(root,'dist');
fs.mkdirSync(out,{recursive:true});
fs.cpSync(path.join(root,'public'),out,{recursive:true});
let base='./';
const url=p=>base+p;
const icon=n=>fs.readFileSync(path.join(root,'public/assets/icons',n+'.svg'),'utf8').replace(/<\?xml[^>]*>/g,'').replace('<svg','<svg aria-hidden="true" focusable="false" class="icon"');
const link=(p,t,c='')=>`<a class="${c}" href="${url(p)}">${t}</a>`;
const photo=(id,alt,cls='',priority=false)=>`<picture class="${cls}"><source type="image/webp" srcset="${[480,960,1600].map(w=>url('assets/images/'+id+'-'+w+'.webp')+' '+w+'w').join(', ')}" sizes="${priority?'100vw':'(max-width: 650px) 100vw, (max-width: 1000px) 50vw, 40vw'}"><img src="${url('assets/images/'+id+'.jpg')}" alt="${alt}" width="1600" height="1200" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async"></picture>`;
const mountainMark='<svg class="icon mountain-mark" viewBox="0 0 160 55" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 50 28 34 42 39 78 3 111 40 129 34 157 49M19 43 43 25 58 30M92 20 102 15 134 43M65 17 77 27 85 20M98 27 109 30 115 29M31 38 43 33 49 39M79 4 75 16"/></svg>';
const brand=()=>`<a class="brand" href="${url('')}" aria-label="Chata Mariánka – úvodní stránka">${mountainMark}<span>CHATA MARIÁNKA</span><small>JIZERSKÉ HORY</small></a>`;
const navigation=[['#o-chate','O chatě'],['ubytovani/','Ubytování'],['fotogalerie/','Fotogalerie'],['okoli/','Okolí'],['cenik/','Ceník'],['kontakt/','Kontakt']];
const nav=()=>navigation.map(([p,t])=>link(p,t)).join('');
const header=home=>`<header class="header ${home?'on-hero':''}"><div class="header-inner">${brand()}<nav class="desktop-nav" aria-label="Hlavní navigace">${nav()}</nav><a class="header-phone" aria-label="Zavolat na +420 777 728 288" href="tel:+420777728288">${icon('phone')}<span>+420 777 728 288</span></a>${link('poptavka/','Poptat termín','button header-cta')}<button class="menu-toggle" aria-label="Otevřít menu" aria-expanded="false" aria-controls="mobile-menu">${icon('menu')}</button></div><nav id="mobile-menu" class="mobile-menu" aria-label="Mobilní navigace" hidden>${nav()}${link('poptavka/','Poptat termín','button')}<a href="tel:+420777728288">+420 777 728 288</a></nav></header>`;
const quick=()=>`<section class="quick-book"><div class="container quick-inner"><div class="quick-title">${icon('calendar-days')}<div><h2>Máte svůj termín?</h2><p>Pošlete nám nezávaznou poptávku.<br>Ozveme se vám co nejdříve.</p></div></div>${link('poptavka/','Poptat termín '+icon('arrow-right'),'button quick-cta')}</div></section>`;
const footer=()=>`<footer class="footer"><div class="forest-edge" aria-hidden="true"></div><div class="container footer-top"><p class="handwriting">Těšíme se na vás v Jizerských horách!</p>${brand()}<address><strong>Chata Mariánka</strong><br>Mariánská Hora 7, Albrechtice v Jizerských horách<br><a href="tel:+420777728288">+420 777 728 288</a><span class="sep">|</span><a href="mailto:roliska@volny.cz">roliska@volny.cz</a></address></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Chata Mariánka</span><nav aria-label="Navigace v zápatí">${link('ubytovani/','Ubytování')}${link('cenik/','Ceník')}${link('kontakt/','Kontakt')}${link('soukromi/','Soukromí a cookies')}${link('zdroje/','Zdroje fotografií')}</nav><a class="credit" href="https://muonity.com/" target="_blank" rel="noopener noreferrer" aria-label="Web by Muonity – otevře se v nové záložce"><img src="${url('assets/images/muonity.png')}" alt="Muonity" width="130" height="43" loading="lazy"></a></div></footer>`;
const schema={ '@context':'https://schema.org','@type':'LodgingBusiness','@id':'https://chatamarianka.cz/#chata',name:'Chata Mariánka',url:'https://chatamarianka.cz/',telephone:'+420777728288',email:'roliska@volny.cz',address:{'@type':'PostalAddress',streetAddress:'Mariánská Hora 7',addressLocality:'Albrechtice v Jizerských horách',postalCode:'468 43',addressCountry:'CZ'},geo:{'@type':'GeoCoordinates',latitude:50.768718,longitude:15.292308},numberOfRooms:5,maximumAttendeeCapacity:21};
function page(route,title,description,body,{home=false,extraHead='',extraScripts='',noindex=false}={}){
 const html=`<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><link rel="canonical" href="https://chatamarianka.cz/${route}">${noindex?'<meta name="robots" content="noindex">':''}<meta name="theme-color" content="#17392d"><meta property="og:type" content="website"><meta property="og:locale" content="cs_CZ"><meta property="og:site_name" content="Chata Mariánka"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="https://chatamarianka.cz/${route}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${description}"><link rel="icon" type="image/svg+xml" href="${url('favicon.svg')}"><link rel="stylesheet" href="${url('assets/fonts/fonts.css')}"><link rel="stylesheet" href="${url('assets/style.css')}">${extraHead}<script type="application/ld+json">${JSON.stringify(schema)}</script><script src="${url('assets/config.js')}" defer></script><script src="${url('assets/app.js')}" defer></script>${extraScripts}</head><body class="${home?'homepage':'inner-page'}"><a class="skip-link" href="#main">Přeskočit na obsah</a>${header(home)}<main id="main">${body}</main>${footer()}</body></html>`;
 const file=route.endsWith('.html')?path.join(out,route):path.join(out,route,'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);
}
const fact=(n,title,text,href='')=>`<${href?'a':'div'} class="fact"${href?` href="${url(href)}"`:''}>${icon(n)}<div><strong>${title}</strong><span>${text}</span></div></${href?'a':'div'}>`;
const card=(id,alt,title,text,cls='')=>`<a class="photo-card ${cls}" href="${url('fotogalerie/')}">${photo(id,alt)}<div class="photo-caption"><strong>${title}</strong><span>${text}</span></div></a>`;
const homeBody=()=>`<section class="hero">${photo('chata-leto','Tradiční horská Chata Mariánka s červenou střechou a zahradou','hero-photo',true)}<div class="hero-shade"></div><div class="container hero-content"><p class="eyebrow">Albrechtice v Jizerských horách</p><h1>Chata Mariánka<span>Klidné ubytování<br>v srdci Jizerek</span></h1><div class="short-rule"></div><p class="hero-copy">Horská chata pro rodiny, přátele i větší skupiny. <br>Až 21 hostů, les za chalupou<br>a krásná příroda Jizerských hor na dosah.</p><div class="hero-actions">${link('poptavka/',icon('calendar-days')+' Poptat termín '+icon('arrow-right'),'button')}${link('fotogalerie/','Prohlédnout chatu','button button-outline')}</div></div><p class="hero-note handwriting" aria-hidden="true">Hory<br>Lidé<br>Zážitky</p><a class="location-tag" href="${url('kontakt/')}">${icon('map-pin')}<span>Mariánská Hora 7,<br>Albrechtice v Jizerských horách</span></a></section><div class="container facts">${fact('users-round','21 hostů','Pohodlné ubytování<br>pro rodiny i skupiny','ubytovani/')}${fact('bed-double','5 pokojů','Všechny s vlastní<br>sprchou a WC','ubytovani/')}${fact('mountain','Jizerské hory','Klidná poloha u lesa,<br>750 m n. m.')}${fact('car-front','Parkování','Přímo před chatou')}</div><section id="o-chate" class="container about"><div class="about-copy"><p class="eyebrow muted">Chata Mariánka</p><h2>Místo,<br>kam se budete <br>rádi vracet</h2><p>Obklopí vás ticho lesa, čistý horský vzduch a jednoduché radosti. Chata Mariánka je místem pro rodiny s dětmi, partu přátel i větší skupiny. Čeká vás útulné zázemí, prostorná společenská místnost a příroda doslova za dveřmi.</p><p class="handwriting">Hory dělají<br>lidi šťastnějšími.</p></div>${card('spolecenska-mistnost','Prostorná jídelna s připraveným slavnostním stolem','Velká společenská místnost','pro oslavy, svatby i firemní akce.','large-card')}<div class="small-cards">${card('pokoj-drevo','Pokoj s dřevěným obložením, lůžky a posezením','Útulné pokoje','s vlastní sprchou a WC.')}${card('ohniste','Kamenné ohniště s dřevěnými lavicemi pod stromy','Posezení u ohniště','v přírodě za chatou.')}</div></section><section class="amenities"><div class="container amenities-inner">${[['shower-head','Vlastní koupelny','ve všech pokojích'],['chef-hat','Vybavená kuchyň','pro vlastní vaření'],['baby','Dětský koutek','pro nejmenší'],['bike','Lyžárna & kola','úschova sportovního vybavení'],['car-front','Parkování','přímo u chaty'],['paw-print','Se psem po domluvě','60 Kč za noc']].map(([i,t,d])=>`<div>${icon(i)}<strong>${t}</strong><span>${d}</span></div>`).join('')}</div></section>`;
const seasonCard=(season,title,description,id,alt,href,button)=>`<a class="season-card" href="${url(href)}">${photo(id,alt)}<div class="season-content"><p>${icon(season==='Léto'?'sun':'snowflake')} ${season}</p><h3>${title}</h3><span class="button button-outline">${button} ${icon('arrow-right')}</span></div></a>`;
const seasons=()=>`<section class="seasons"><div class="container"><div class="season-heading"><div><p class="eyebrow">V létě i v zimě</p><h2>Jizerské hory po celý rok</h2></div><p>Ať už milujete turistiku, cyklistiku, běžky nebo sjezdovky,<br>Jizerské hory mají co nabídnout v každém ročním období.<br>Chata Mariánka je výchozím bodem pro vaše zážitky.</p></div><div class="season-grid">${seasonCard('Léto','Turistika, cyklistika,<br>nekonečné výhledy','','jizerky-leto','Letní výhled z Paličníku do Jizerských hor','okoli/#leto','Objevovat okolí')}${seasonCard('Zima','Běžky, sjezdovky,<br>Jizerská magistrála','','jizerky-zima','Upravené běžecké stopy u Nového Města pod Smrkem','okoli/#zima','Zimní tipy')}<div class="season-highlights">${fact('mountain','Tanvaldský Špičák','cca 2,5 km podle webu chaty<br>oblíbený lyžařský areál')}${fact('signpost','Jizerská magistrála','nástup z Mariánské Hory<br>výlety po běžeckých tratích')}${fact('tree-pine','Turistické a cyklistické trasy','les hned za chalupou<br>příroda Jizerských hor')}</div></div></div></section>`;
page('','Chata Mariánka | Klidné ubytování v Jizerských horách','Horská Chata Mariánka v Albrechticích v Jizerských horách. 21 lůžek, 5 pokojů s vlastní koupelnou, kuchyň a les za chalupou. Poptat pobyt.',homeBody()+seasons()+quick(),{home:true});
renderPages({page,url,icon,link,photo,quick,root,out,setBase:value=>{base=value;}});
const routes=['','ubytovani/','cenik/','fotogalerie/','okoli/','kontakt/','poptavka/','soukromi/','zdroje/'];
fs.writeFileSync(path.join(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>'<url><loc>https://chatamarianka.cz/'+r+'</loc></url>').join('')+'</urlset>');
fs.writeFileSync(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://chatamarianka.cz/sitemap.xml\n');
fs.writeFileSync(path.join(out,'.nojekyll'),'');
console.log('Web sestaven: '+out);



